
Description: The dataset contains more than 120 thousands movies from 1911 to 2024, present on IMDB.

Task: Clean it and do exploratory data analysis on it.Day
Today, I am introducing you to the concept of "User Stories". It helps to guide you even more on what to do with our dataset. For the Dataset above, you are required to work according to the following user stories:

1) As a film enthusiast, I want to identify the top-rated movies across different genres, so that I can discover new high-quality films to watch.

2) Analyze Cast and Crew Relationships:
As a movie producer, I want to identify frequently collaborating actors, directors, or writers to understand successful filmmaking teams. TIP: Develop a network visualization showcasing frequent collaborators among actors, directors, and writers.

3) As a marketing manager, I want to understand how user engagement (number of ratings) changes over time and identify genres with the most engaged audiences.
Acceptance criteria: Generate charts illustrating the average number of ratings per year and compare it across different genres.

Try these and we shall continue with more later on

Good luck ladies

## Data Cleaning

In [28]:
import pandas as pd

In [29]:
movies = pd.read_csv('/content/drive/MyDrive/Colab Notebooks gogirl/csv_files/movies_imdb.csv')

In [30]:
movies.shape

(126691, 12)

In [31]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126691 entries, 0 to 126690
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Movie URL      126691 non-null  object
 1   Title          126626 non-null  object
 2   Poster         126384 non-null  object
 3   Release Year   126618 non-null  float64
 4   Length in Min  124733 non-null  float64
 5   IMDB Rating    126624 non-null  float64
 6   Rating Count   126624 non-null  float64
 7   Plot           126626 non-null  object
 8   Directors      125842 non-null  object
 9   Writers        119634 non-null  object
 10  Stars          125339 non-null  object
 11  Genres         126515 non-null  object
dtypes: float64(4), object(8)
memory usage: 11.6+ MB

In [32]:
movies.describe(include='all')

,Movie URL,Title,Poster,Release Year,Length in Min,IMDB Rating,Rating Count,Plot,Directors,Writers,Stars,Genres
count,126691,126626,126384,126618.000000,124733.000000,126624.000000,1.266240e+05,126626,125842,119634,125339,126515
unique,126691,118227,126352,NaN,NaN,NaN,NaN,124474,64160,97091,123775,1407
top,https://www.imdb.com/title/tt0001892/?ref_=sr_t_3,Solo,https://m.media-amazon.com/images/M/MV5BOTg3Mj...,NaN,NaN,NaN,NaN,Add a plot in your language,Michael Curtiz|,Jing Wong|,Penny Singleton|Arthur Lake|Larry Simms,Drama
freq,1,12,4,NaN,NaN,NaN,NaN,2048,85,106,28,16878
mean,NaN,NaN,NaN,1997.355273,100.190046,5.917401,8.803425e+03,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,24.529791,192.061473,1.277181,5.615486e+04,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,1903.000000,17.000000,1.000000,9.900000e+01,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,1984.000000,87.000000,5.200000,1.980000e+02,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,2007.000000,95.000000,6.100000,4.650000e+02,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,2016.000000,108.000000,6.800000,1.700000e+03,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,2023.000000,51420.000000,9.900000,2.900000e+06,NaN,NaN,NaN,NaN,NaN

In [33]:
movies.duplicated().sum()

0

In [34]:
movies['Title'].duplicated().sum()

8463

In [35]:
movies[movies['Title'].duplicated()]

,Movie URL,Title,Poster,Release Year,Length in Min,IMDB Rating,Rating Count,Plot,Directors,Writers,Stars,Genres
120,https://www.imdb.com/title/tt0007801/?ref_=sr_t_1,Cleopatra,https://m.media-amazon.com/images/M/MV5BMGQ2MG...,1917.0,125.0,6.6,394.0,"The story of Cleopatra, the fabulous queen of ...",J. Gordon Edwards|,H. Rider Haggard|Adrian Johnson|Émile Moreau|,Theda Bara|Fritz Leiber|Thurston Hall,Biography|Drama|History
165,https://www.imdb.com/title/tt0008950/?ref_=sr_t_7,Carmen,https://m.media-amazon.com/images/M/MV5BMzZkYm...,1918.0,70.0,5.9,405.0,"The tragic story of Don Jose, a Spanish cavalr...",Ernst Lubitsch|,Prosper Mérimée|Hanns Kräly|Grete Diercks|,Pola Negri|Harry Liedtke|Sophie Pagay,Drama
401,https://www.imdb.com/title/tt0013597/?ref_=sr_t_9,Sherlock Holmes,https://m.media-amazon.com/images/M/MV5BMjE4Nz...,1922.0,85.0,5.7,731.0,A young Sherlock Holmes seeks to bring down th...,Albert Parker|,Earle Browne|Arthur Conan Doyle|Marion Fairfax|,John Barrymore|Roland Young|Carol Dempster,Drama|Mystery
405,https://www.imdb.com/title/tt0013662/?ref_=sr_...,Tess of the Storm Country,https://m.media-amazon.com/images/M/MV5BMTgxMT...,1922.0,137.0,7.0,517.0,Wealthy Elias Graves builds his home on the to...,John S. Robertson|,Grace Miller White|E. Lloyd Sheldon|Josephine ...,Mary Pickford|Lloyd Hughes|Gloria Hope,Drama|Romance
503,https://www.imdb.com/title/tt0015253/?ref_=sr_...,Quo Vadis?,https://m.media-amazon.com/images/M/MV5BMTU0Nz...,1924.0,90.0,5.9,102.0,"In Rome, during the reign of Nero, a young pag...",Gabriellino D'Annunzio|Georg Jacoby|,Gabriellino D'Annunzio|Georg Jacoby|Henryk Sie...,Emil Jannings|Elena Sangro|Rina De Liguoro,Drama
...,...,...,...,...,...,...,...,...,...,...,...,...
126666,https://www.imdb.com/title/tt2785032/?ref_=sr_...,The Little Death,https://m.media-amazon.com/images/M/MV5BYjUxOT...,2014.0,96.0,7.0,28000.0,The secret lives of five suburban couples livi...,Josh Lawson,Josh Lawson|,Bojana Novakovic|Josh Lawson|Damon Herriman,Comedy|Drama|Romance
126667,https://www.imdb.com/title/tt27850479/?ref_=sr...,Revenge,https://m.media-amazon.com/images/M/MV5BNjQzMT...,2023.0,102.0,7.0,1400.0,A drug addicted Serial killer Kali kills women...,Rettadi Shrinivas|,NaN,Babu Pedapudi|Neha Pandey|Bhargav,Action
126672,https://www.imdb.com/title/tt2785464/?ref_=sr_...,Angel,https://m.media-amazon.com/images/M/MV5BMzZjYj...,2015.0,83.0,4.3,322.0,"Angel, a woman who was horribly abused by her ...",Ray Burdis,Ray Burdis|,John Hannah|Margo Stilley|Karel Roden,Thriller
126677,https://www.imdb.com/title/tt2786278/?ref_=sr_...,Amen,https://m.media-amazon.com/images/M/MV5BN2Y2Yj...,2013.0,165.0,7.9,3500.0,Amen tells the story of people around an ancie...,Lijo Jose Pellissery|,P.S. Rafeeque|Lijo Jose Pellissery|,Fahadh Faasil|Indrajith Sukumaran|Kalabhavan Mani,Drama|Romance
126685,https://www.imdb.com/title/tt27873991/?ref_=sr...,Abhilasha,https://m.media-amazon.com/images/M/MV5BODBkNW...,2023.0,133.0,7.7,1200.0,SRIRAM WHO IS A BTECH GRADUATE GROWN UP UNDER ...,Siva Prasad Chaluvadi|,NaN,Ashwini Reddy|Darbha Appaji Ambarisha|Amardeep...,Action

In [36]:
movies['Poster'].duplicated().sum()

338

In [37]:
movies.isna().sum()

Movie URL           0
Title              65
Poster            307
Release Year       73
Length in Min    1958
IMDB Rating        67
Rating Count       67
Plot               65
Directors         849
Writers          7057
Stars            1352
Genres            176
dtype: int64

In [38]:
movies[movies['Title'].duplicated() & movies['Length in Min'].isna()].shape

(179, 12)

In [39]:
movies[movies['Title'].duplicated() & movies['Plot'].isna()].shape

(64, 12)

In [40]:
movies[movies['Title'].duplicated() & movies['Genres'].isna()].shape

(72, 12)

In [45]:
movies.dropna(subset=['Title'], inplace=True)

In [46]:
movies.isna().sum()

Movie URL           0
Title               0
Poster            242
Release Year        8
Length in Min    1893
IMDB Rating         2
Rating Count        2
Plot                0
Directors         784
Writers          6992
Stars            1287
Genres            111
dtype: int64

In [47]:
movies['Release Year'].fillna(method='ffill', inplace=True)

In [48]:
movies.dropna(subset= ['IMDB Rating'], inplace=True)

In [49]:
movies.isna().sum()

Movie URL           0
Title               0
Poster            242
Release Year        0
Length in Min    1893
IMDB Rating         0
Rating Count        0
Plot                0
Directors         784
Writers          6992
Stars            1287
Genres            111
dtype: int64

##User story 1:  As a film enthusiast, I want to identify the top-rated movies across different genres, so that I can discover new high-quality films to watch.

In [64]:
# movies.groupby('Genres').sort_values('IMDB Rating', ascending=True)
# sorted_movies = movies.sort_values(['Genres', 'IMDB Rating'], ascending=[True, False])
# sorted_movies

movies.sort_values('IMDB Rating', ascending=False).groupby('Genres').head(1)

,Movie URL,Title,Poster,Release Year,Length in Min,IMDB Rating,Rating Count,Plot,Directors,Writers,Stars,Genres
126211,https://www.imdb.com/title/tt27426876/?ref_=sr...,Nannayikoode,https://m.media-amazon.com/images/M/MV5BM2JjNT...,2023.0,NaN,9.9,109.0,"The film is in speculative family genre, in a ...",Janet J,Janet J|,Sooraj Thelakkadu|Kannan|Arathy KB,Drama
93191,https://www.imdb.com/title/tt11076052/?ref_=sr...,Electric Burma,https://m.media-amazon.com/images/M/MV5BZjlkMz...,2012.0,54.0,9.8,207.0,A documentary of the concert in honor of freed...,Natalie Johns|,NaN,Nazanin Afshin-Jam|Zachary Alford|Arden Altino,Documentary
125716,https://www.imdb.com/title/tt26754306/?ref_=sr...,Ondolle Love Story,https://m.media-amazon.com/images/M/MV5BY2I2YT...,2023.0,NaN,9.8,107.0,This generation gets addicted to alcohol and d...,Praveen Sutar,Mahesh B Patil|,Niranjan Babu|Dhanushree V|Nisha Hegde,Drama|Romance
2640,https://www.imdb.com/title/tt28660608/?ref_=sr...,Ardhambardha Premakathe,https://m.media-amazon.com/images/M/MV5BMjBhOT...,2023.0,136.0,9.8,337.0,A handsome boy and a beautiful girl end up in ...,Aravind Kaushik,Aravind Kaushik|,Abhilash M|Dwarish Abhilash|K.P. Aravind,Comedy|Romance
2722,https://www.imdb.com/title/tt28766081/?ref_=sr...,Mukalpparappu,https://m.media-amazon.com/images/M/MV5BMDE0Ym...,2023.0,144.0,9.7,287.0,Priyesh who is an engineering graduate is the ...,Siby Padiyara,Siby Padiyara|,Lishoy|Mammukoya|Unni Raja,Family
...,...,...,...,...,...,...,...,...,...,...,...,...
98977,https://www.imdb.com/title/tt12631030/?ref_=sr...,Battle of the Bulge: Winter War,https://m.media-amazon.com/images/M/MV5BN2QyNT...,2020.0,85.0,2.7,571.0,"During World War II, the Germans decide to lau...",Steven Luke,Steven Luke|,Steven Luke|Tom Berenger|Billy Zane,Fantasy|War
67317,https://www.imdb.com/title/tt0211380/?ref_=sr_...,Le führer en folie,https://m.media-amazon.com/images/M/MV5BMGRkZm...,1974.0,95.0,2.5,108.0,France and Germany are at war. Adolf Hitler ch...,Philippe Clair|,Anita Benzaquen|Victor Béniard|Philippe Clair|,Alice Sapritch|Henri Tisot|Luis Rego,Comedy|Sport|War
13043,https://www.imdb.com/title/tt4656810/?ref_=sr_...,The Broken Key,https://m.media-amazon.com/images/M/MV5BOWE0Mz...,2017.0,125.0,2.4,437.0,"In a near future, due to the effects of an unc...",Louis Nero|,Louis Nero|Giancarlo Guerreri|As Chianese|,Rutger Hauer|Michael Madsen|Christopher Lambert,History|Sci-Fi|Thriller
121333,https://www.imdb.com/title/tt2265116/?ref_=sr_...,The Medic,https://m.media-amazon.com/images/M/MV5BMjA1MT...,2013.0,85.0,2.3,374.0,A squad of Canadian soldiers survive a helicop...,Aaron Kurmey|,Ryan Hatt|Kevin Johnson|Aaron Kurmey|,Ryan Agnew|Antonio Aguirre|Mark Campbell,Action|Sci-Fi|War
70041,https://www.imdb.com/title/tt0256345/?ref_=sr_...,Rock of Ages,https://m.media-amazon.com/images/M/MV5BZmQ4OT...,1984.0,NaN,1.5,271.0,Add a plot in your language,Tony Klinger,Tony Klinger|,Peter Dawson|Kevin Mann|Aixa Moreno,Music|Sci-Fi|Thriller

In [71]:
movies['Genres'].unique().size

1408

## User story 2: Analyze Cast and Crew Relationships: As a movie producer, I want to identify frequently collaborating actors, directors, or writers to understand successful filmmaking teams. TIP: Develop a network visualization showcasing frequent collaborators among actors, directors, and writers.